### ISSUE TITLE
 No such file or directory

### ISSUE THREAD

**Issue by jcqbrc** [chbrown/overdrive#12]
Hello!

Really looking forward to being able to use this tool, but when I enter the commands, I receive the following: 

```
sudo chmod +x /usr/local/bin/overdrive
chmod: /usr/local/bin/overdrive: No such file or directory
```

I've tried separating out the commands (as you mentioned in another issue), as far as I can tell, but I always get stopped with the "No such file..." error. 

Any thoughts on why this would be the case? Thanks so much for making this tool for those of us that updated to Catalina!

**Comment by chbrown** [comment]
Hi, thanks for your interest! You're not alone among Catalina converts :) — please see #11, which I think should cover your mishap. I plan to refactor the Q&A there into the repo's README, but it'd be really helpful if you could report back which solution was the easiest / most reliable?
