### ISSUE TITLE
Deprecate tidy

### ISSUE THREAD

**Issue by chbrown** [chbrown/overdrive#14]
Try to find an alternative to `tidy`. 

It's only used in one place, in the `extract_metadata` function, to sanitize the metadata XML.

macOS comes with an old version (2006-10-31) of `tidy`:
```sh
/usr/bin/tidy -v
```
> HTML Tidy for Mac OS X released on 31 October 2006 - Apple Inc. build 16.4

so for the most part it does _work_, but `tidy` is finicky and opinionated and not exactly stable.

**Comment by 9mido** [comment]
Not sure but here are some ideas:

https://stackoverflow.com/questions/1732348/regex-match-open-tags-except-xhtml-self-contained-tags

https://stackoverflow.com/questions/4680143/how-to-parse-xml-using-shellscript

https://docs.raku.org/language/grammars
