### ISSUE TITLE
Replace post-processor with FFMPEG

### ISSUE THREAD

**Issue by lincalinca** [chbrown/overdrive#17]
You don't need to use mutagen for tagging, FFMPEG will work just fine using the `-metadata` command.

It's all spelled out pretty well in this guide: https://gist.github.com/eyecatchup/0757b3d8b989fe433979db2ea7d95a01
(note: not the official user guide, but arguably better written than the official docs on this specific topic).

**Comment by chbrown** [comment]
Cool, thanks for the info and the pointer to that helpful-looking guide :)
