### ISSUE TITLE
parser error : Document is empty

### ISSUE THREAD

**Issue by rmlrml** [chbrown/overdrive#21]
overdrive.sh successfully downloads 6 out of 10 parts but then tells me "...metadata:1: parser error : Document is empty".  I realized from the first error output that the command "tidy" was not installed, so I installed it and tried overdrive.sh again, no dice.  Here is the output:

```
ryan@pocketwee:~/Books$ overdrive download DontBurnThisBookThinkingforYourselfinAnAgeofUn-683.odm 
License already acquired: DontBurnThisBookThinkingforYourselfinAnAgeofUn-683.odm.license
Using License=<License xmlns="http://license.overdrive.com/2008/03/License.xsd" xmlns:i="http://www.w3.org/2001/XMLSchema-instance"><SignedInfo><Version>1.0</Version><ContentID>d1ef3dc1-c3b0-4a09-a89d-fbb31252a84a-425</ContentID><ClientID>E54A3A57-40E2-4F2F-928D-EA665B9B5872</ClientID></SignedInfo><Signature>MmaVqIzcTm5sA8pbZoGYbt4DonXUiG+fm+Cwp9lGS7c3CnxM/OYArYqi5lH40mfXdTcT0hQPYF5F2avDdHE/EAqczJus9fssGMBgy946DtTH8ca+pCuX1tZExctFOmIrQPxnhIdMkB4IJMd4MZVYhSZyKmm/8PDhq2HzAcRnn6o=</Signature></License>
Using ClientID=E54A3A57-40E2-4F2F-928D-EA665B9B5872 from License
DontBurnThisBookThinkingforYourselfinAnAgeofUn-683.odm.metadata:1: parser error : Document is empty

^
seq: invalid floating point argument: ‘’
Try 'seq --help' for more information.
Using Author=
DontBurnThisBookThinkingforYourselfinAnAgeofUn-683.odm.metadata:1: parser error : Document is empty

^
Using Title=
Creating directory  - 
Output already exists:  - /Part01.mp3
Output already exists:  - /Part02.mp3
Output already exists:  - /Part03.mp3
Output already exists:  - /Part04.mp3
Output already exists:  - /Part05.mp3
Output already exists:  - /Part06.mp3
DontBurnThisBookThinkingforYourselfinAnAgeofUn-683.odm.metadata:1: parser error : Document is empty

^
Using CoverUrl=
Cover image not available
ryan@pocketwee:~/Books$ 
```

**Comment by chbrown** [comment]
Can you delete the `*.odm.metadata` file and retry?

**Comment by rmlrml** [comment]
Done.  This time again it only downloaded 6 parts, but with no error message.  I played the files and realized the mp3 part divisions did not correspond to the 10 book chapters -- there are multiple chapters in each mp3 "part".  The issue was never an issue.  I'm sorry for taking up your time!

**Comment by chbrown** [comment]
No problem! Glad you got it working. Also, good to know that I can't assume there will be _some_ version of `tidy` installed; on macOS (Mojave) there is a system-provided `tidy` in `/usr/bin`, which is very old (see #14), but suffices.

I'm guessing you're on linux? (Or maybe Catalina, and Catalina dropped `tidy`?)

**Comment by rmlrml** [comment]
Yes, Debian 10 buster (stable).  BTW before that I also had to install package `uuid-runtime` which provides uuidgen and package `libxml2-utils` which provides xmllint, as neither of those had been installed.  Can't say for sure whether they had not ever been installed in the default OS setup, or possibly had been but had gotten removed with something else I had removed, but there you go.
