### ISSUE TITLE
overdrive: xmlstarlet: command not found

### ISSUE THREAD

**Issue by AlpacaLips99** [chbrown/overdrive#22]
Hey chbrown! I was an avid Overdrive user and I'm using your overdrive thingie to brace myself for the upgrade to Catalina which breaks Overdrive. I'm a noob to GitHub and pretty much even Terminal, but I'm fearless. I followed the instructions to install it, borrowed a book an downloaded the .odm. Issued the command and got the xmlstarlet command not found. Maybe there's some kind of developer commands I don't have installed. Can you help?

I created a gist but I'm not sure of the proper protocol for giving it to you so I'll include the embed link and the verbose text itself.
<script src="https://gist.github.com/AlpacaLips99/212e18504eec99f1bdbb2b9f4269d82f.js"></script>

Corys-MacBook-Pro:Downloads coryengel$ overdrive download WakingGodsThemisFilesSeriesBook02-63028.odm --verbose
+ printf 'Entering debug (verbose) mode\n'
Entering debug (verbose) mode
+ shift
+ [[ 0 -gt 0 ]]
+ [[ 1 -eq 0 ]]
+ [[ 1 -eq 0 ]]
+ HEADER_PRINTED=
+ for ODM in '"${MEDIA[@]}"'
+ for COMMAND in '"${COMMANDS[@]}"'
+ case $COMMAND in
+ download WakingGodsThemisFilesSeriesBook02-63028.odm
+ license_path=WakingGodsThemisFilesSeriesBook02-63028.odm.license
+ acquire_license WakingGodsThemisFilesSeriesBook02-63028.odm WakingGodsThemisFilesSeriesBook02-63028.odm.license
+ [[ -e WakingGodsThemisFilesSeriesBook02-63028.odm.license ]]
++ uuidgen
++ tr '[:lower:]' '[:upper:]'
+ ClientID=FB5EB1EB-7305-4845-A4B8-EA005CC5D5DE
+ printf 'Generating random ClientID=%s\n' FB5EB1EB-7305-4845-A4B8-EA005CC5D5DE
Generating random ClientID=FB5EB1EB-7305-4845-A4B8-EA005CC5D5DE
++ xmlstarlet sel -t -v /OverDriveMedia/License/AcquisitionUrl WakingGodsThemisFilesSeriesBook02-63028.odm
/usr/local/bin/overdrive: line 70: xmlstarlet: command not found
+ AcquisitionUrl=

**Comment by AlpacaLips99** [comment]
NEVERMIND! I found and installed XMLStarlet... All is well.

**Comment by chbrown** [comment]
Glad you figured it out :)

FYI, as of 0b92b55 (Dec 14, 2019) the script doesn't use `xmlstarlet` anymore, so it sounds like you're on an old version.

"If it ain't broke, don't fix it" — but if you run into any (other) trouble, I'd recommend installing the latest version.

**Comment by AlpacaLips99** [comment]
Well now, that’s weird because I downloaded it tonight for the first time.

**Comment by chbrown** [comment]
Huh, that's super weird. 

I could see GitHub's CDN getting a couple hours out of date, but nearly half a year? 🤨

**Comment by AlpacaLips99** [comment]
I did find it odd that xmlstarlet was not listed among the prerequisites.

Any suggestions on a good MacOS mp3 tag editor now that iTunes is defunct?

**Comment by chbrown** [comment]
IDK? still happily on Mojave, personally, with a fully functioning iTunes

**Comment by AlpacaLips99** [comment]
Wish I could say the same thing. Unfortunately I finally concluded that the pain of upgrading was less than the pain of not upgrading. Thanks in part to your script. :)

**Comment by AlpacaLips99** [comment]
Hey while I have your attention… I don’t suppose there’s a way to specify what folder to download the MP3s to?

I mean… without learning to code.

**Comment by chbrown** [comment]
The destination folder is whatever folder your shell is currently in (run `pwd` to show it).

I usually run something like:
```sh
cd ~/Music/Audiobooks && overdrive download ~/Downloads/*.odm
```
You can replace the `~/Music/Audiobooks` part with whatever (existing) folder you want.
