### ISSUE TITLE
overdrive command not found

### ISSUE THREAD

**Issue by ernasheree** [chbrown/overdrive#42]
After installing and then trying to download the book, it tells me "zsh: command not found: overdrive". I'm closed Terminal and reinstalled the first command with the same result. Help please.

**Comment by chbrown** [comment]
Please read the rest of the "Install" section, and report back with a detailed description of what you've tried and what results you got in the terminal at each step.

**Comment by ernasheree** [comment]
So I attempted to delete this post 2 minutes after making it because I saw the rest of the instructions. For some reason, I thought those were for error messages upon the initial installation of overdrive. All good now and I've got my audiobooks downloaded. Thank you!
