### ISSUE TITLE
linux support

### ISSUE THREAD

**Issue by mlybarger** [chbrown/overdrive#44]
i'm on linux and trying this out.  i got some odm files from the library, and tried to download the mp3.  it seems i'm getting an empty .metadata file. the error is:

`.odm.metadata:1: parser error : Document is empty
`

i see a .metadata file, but it's indeed empty. any ideas or helps on what to try?

**Comment by chbrown** [comment]
Delete the metadata file, and retry with `--verbose` flag. You might be missing some prereq.

**Comment by chbrown** [comment]
Assuming that this was due to missing a prereq. Latest commits should make that more clear (9e539ce), and avoid having to manually delete the empty file (ab1dfcc). Please reopen if I assume wrong.

**Comment by mlybarger** [comment]
thanks. i pulled the latest, removed the metadata file and it works!
