### ISSUE TITLE
Libraries omitting ODM download links

### ISSUE THREAD

**Issue by mattppal** [chbrown/overdrive#45]
It seems like OverDrive is moving away from allowing access ODM files. One particular library I use no longer has an option to download them from their site.

Is there a way to get access to the ODM data from the audiobook ID? e.g. `XXXX.listen.overdrive.com`?

**Comment by chbrown** [comment]
Yeah I've noticed that too — worrying trend, but there are workarounds (for now). Easiest is probably to try setting your browser User-Agent to look like you're using Windows.

Other users might have other methods? (I wish I could ping my star-ers like a $lack channel to ask for advice, because this question is definitely outside the scope of this codebase, but very relevant to the userbase.)

**Comment by chbrown** [comment]
FWIW, I use https://chrome.google.com/webstore/detail/lkmofgnohbedopheiphabfhfjgkhfcgf and https://techblog.willshouse.com/2012/01/03/most-common-user-agents/ to override my User-Agent in Chrome.

**Comment by mattppal** [comment]
Thanks, I have a user-agent switcher. Firefox windows seemed to do the trick!

With Overdrive depreciating their Mac app and limiting the number of routes to get ODM files, it seems like they're trying to phase out downloads and force users to Libby/streaming.

I'll keep an eye on this thread for other suggestions, thanks for your help 👍

**Comment by chbrown** [comment]
Btw, just added a note to this effect in the [README](https://github.com/chbrown/overdrive#common-errors), but I'm gonna leave the issue open for a while in case anyone else knows of alternatives.

**Comment by johngully** [comment]
I tried using the chrome extension to modify my user-agent and I'm not seeing the download button.  I've tried a couple of variations including Firefox on Windows and a Mac Mojave Safari version without success. Am I doing it wrong or have they changed the library websites to limit downloads even further?  
 
 Can anyone else confirm that changing the user-agent works?  If so which string did you use?

**Comment by choc96208** [comment]
OverDrive asks you whether you have the OverDrive app install on your computer. I clicked the arrow to say yes. It then allowed me to download the odm file. I changed my user agent manually by going to:
`about:config`
then creating the string 
`general.useragent.override`
with
`Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_4) AppleWebKit/605.1.15 (KHTML, like Gecko)`
which I found from [whatismybrowser.com](https://web.archive.org/web/20211106181212/https://developers.whatismybrowser.com/useragents/explore/operating_system_name/macos/).

**Comment by mattppal** [comment]
@johngully I can confirm they added an additional step. The Mac Overdrive app is no longer available, but there is a Windows version. Thus, you must select a user agent for Windows. For me, Windows Firefox 33 yields the following image, where I can download the titles. It appears they added an extra step. I wouldn't be surprised if they close this method off soon as well.

![image](https://user-images.githubusercontent.com/59450879/155719011-dc384aa2-e3b5-4070-8e7d-40acd74a381e.png)

**Comment by johngully** [comment]
Thanks for the help. It was the need to expand the "Do you have the Overdrive App" accordion that I was missing. I'm good to go now!

**Comment by johngully** [comment]
I have been using this script for a while to help access audiobooks I have borrowed from my local library through Overdrive.  With the increased difficulty of access to the mp3 downloads I [created a project to make things a little easier](https://github.com/johngully/overdrive-download) on everyone.  It's a  `node v17+` based project that creates a command line utility that simplifies the process of both acquiring the `.odm` and downloading the `.mp3` files.  Once you have a book on loan in your Overdrive account, this command will take care of the rest.  It's pretty early (I'm the only one using it), but wanted to share and see if anyone else found it helpful.

I have attempted to make Installing and getting setup fairly straight forward as long as you are running
```bash
npm install -g overdrivedownload
odm config -l example-library-name -u example-username -p example-password -dl "./example/dowload/path"
odm "Title of book"
```


Big thanks to @chbrown and the work done here!  My code is really standing on the shoulders of folks way smarter than me :)

**Comment by arnavdugar** [comment]
For anyone that has only a link (e.g. from a library page), I created a script that will download the mp3s from the link:
https://github.com/arnavdugar/odm

**Comment by Elsto007** [comment]
How do I extract the “Listen now in browser” link from the Libby Library app in order to apply your script?

**Comment by Elsto007** [comment]
﻿﻿Hi,How do you currently take out audiobooks from your public library and extract the odm/mp3 files then?  I use to use Overdrive but that option is retired and replaced with Libby?   Just until recently, in Overdrive app had the Listen In Browser Now.  I’ll have to check to see of the Libby app has that option too.Thanks.Sent from my iPadOn May 31, 2023, at 4:56 PM, Arnav Dugar ***@***.***> wrote:﻿
Hi, I might be doing something differently than you. I don't have the Libby app. Instead, once I check out the audiobook from the library, there's a button to "listen now in browser". I'm using the link for that button.
