### ISSUE TITLE
syntax error near unexpected token `newline' when downloading an .odm file

### ISSUE THREAD

**Issue by mescler** [chbrown/overdrive#47]
Hi @chbrown,

Thank you for creating an amazing OverDrive script that is so helpful! I am getting the following error when I try and download an .odm file. I did not see others with a similar issue. I have tried a few .odm files from my local library. Here are the commands and responses. I also attached the .odm file (not I had to change the extension to .zip to upload, but you can just change it back to .odm). 

MacBook-Air:Downloads kmesser$ ~/.local/bin/overdrive download /Users/kmesser/Downloads/Sentence.odm 
/Users/kmesser/.local/bin/overdrive: line 1: syntax error near unexpected token `newline'
/Users/kmesser/.local/bin/overdrive: line 1: `<!DOCTYPE html>'

Thanks so much for the help!
[Sentence.zip](https://github.com/chbrown/overdrive/files/8212160/Sentence.zip)

Adam

**Comment by chbrown** [comment]
It looks like you installed the script wrong — you presumably saved the GitHub webpage that displays the source code, instead of just the source code.

If you follow the [instructions](https://github.com/chbrown/overdrive#instructions), that should fix it.
