### ISSUE TITLE
Ubuntu bash on WSL hates returns

### ISSUE THREAD

**Issue by rgalverson** [chbrown/overdrive#48]
Kudos!  I got this working on Ubuntu on WSL with Win10.  Only notable issue I had was the overdrive.sh script has carriage returns as well as newlines.  I ran it through sed to delete the returns (s/\r//) and now it seems to be working.

**Comment by chbrown** [comment]
Uhhh, `curl https://chbrown.github.io/overdrive/overdrive.sh | xxd | head`:
```
00000000: 2321 2f75 7372 2f62 696e 2f65 6e76 2062  #!/usr/bin/env b
00000010: 6173 680a 0a73 6574 202d 6520 2320 6578  ash..set -e # ex
00000020: 6974 2069 6d6d 6564 6961 7465 6c79 206f  it immediately o
00000030: 6e20 6669 7273 7420 6572 726f 720a 7365  n first error.se
00000040: 7420 2d6f 2070 6970 6566 6169 6c20 2320  t -o pipefail #
00000050: 7072 6f70 6167 6174 6520 696e 7465 726d  propagate interm
00000060: 6564 6961 7465 2070 6970 656c 696e 6520  ediate pipeline
00000070: 6572 726f 7273 0a0a 2320 7368 6f75 6c64  errors..# should
00000080: 206d 6174 6368 2060 6769 7420 6465 7363   match `git desc
00000090: 7269 6265 202d 2d74 6167 7360 2077 6974  ribe --tags` wit
```
I don't see any `0d` in there...

I guess if your download method added them, and your bash doesn't like them, then yeah, you'll have to delete them. But they're not coming from the repo.
