### ISSUE TITLE
any idea how we can use libby?

### ISSUE THREAD

**Issue by test2a** [chbrown/overdrive#51]
![Screenshot 2022-09-22 at 10-59-01 Libby - Rather Be the Devil](https://user-images.githubusercontent.com/39449563/191665522-353b52f1-b7d5-4aaa-983c-5b0627db8fd5.png)

as many people already know, overdrive is being phased out after years of being assured that both overdrive and libby will continue side by side. anyways, this is the screen on libby via their website. 
This means when overdrive will sunset, we will be left with no way to download mp3s. Has anyone found a way to de-drm libby files?

**Comment by chbrown** [comment]
The direction they're taking is disappointing to all of us, but I'm sorry, this isn't the appropriate forum for your question. 

This repo has no interest in circumventing DRM. 

Maybe try https://www.reddit.com/r/audiobooks/

**Comment by test2a** [comment]
@chbrown 
https://www.reddit.com/r/audiobooks/comments/todkr0/transferring_audiobooks_to_mp3_player_from_libby/

https://www.reddit.com/r/audiobooks/comments/todkr0/comment/i25nosg/?utm_source=share&utm_medium=web2x&context=3

i tried the android thing and it really does have mp3 files, just severely obfuscated with long names. 

the thread https://www.reddit.com/r/audiobooks/comments/todkr0/comment/img5tu1/?utm_source=share&utm_medium=web2x&context=3 mentions a jar file which i did download and use but that probably has bugs currently so that did not work right now but this is not totally difficult to work with i can assume..

my initial assumption about DRM was incorrect, they do pass mp3 files, just with weird names.

we would need to have a way to find the correct order of the files and rename them accordingly so can we run some tests?
