### ISSUE TITLE
Libby

### ISSUE THREAD

**Issue by ascii1b-pixel** [chbrown/overdrive#53]
Hi. I've really enjoyed using your script over the last couple of years.
Have you, by chance, looked at the new Libby app? It looks like Overdrive is going away in January 2023 and Libby doesn't allow direct downloading of any files.

Just wondered if you've given it any thought?

Thanks

**Comment by chbrown** [comment]
I've just added a "Libby" section to the README to address this and similar questions (you are not alone!):

* https://github.com/chbrown/overdrive#libby

**tl;dr:** I've given it some thought, yes, but personally I'm not gonna worry about it until they actually pull the trigger.
