### ISSUE TITLE
Does this work in Windows?

### ISSUE THREAD

**Issue by hub2git** [chbrown/overdrive#54]
I used this in Linux, but does this work in Windows too?
If it doesn't, can anyone recommend a Windows program that works.

**Comment by chbrown** [comment]
> I used this in Linux, but does this work in Windows too? 

Idk, try it and see? 

Not a Windows ~victim~ user myself, but isn't this exactly what [WSL](https://learn.microsoft.com/en-us/windows/wsl/) is for?

> If it doesn't, can anyone recommend a Windows program that works.

Will leave this open for a bit longer in case anyone wants to chime in, but this isn't really the right place for this question.

**Comment by afonsoguerra** [comment]
This is a bash script, so any sort of half-complete bash implementation in windows should do the trick. WSL is probably the most robust, especially if you are already proficient in Linux. Before WSL there were already alternatives like Cygwin and MinGW. 
Last but not the least, you should be able to get a linux instance somewhere on the cloud for free where you can upload the odm file through ssh, run the original script and retrieve the mp3 without too much trouble…
