### ISSUE TITLE
Python CLI for Libby - link to repo

### ISSUE THREAD

**Issue by lullius** [chbrown/overdrive#55]
Hi, great project you have here. 
I noticed that you updated the readme on the topic of Libby the other day. I'm not trying to steal attention away from this project, I just wanted to show you what I've been working on lately now that it's clear that the legacy OverDrive app is being discontinued in early 2023 and odm's might go away.

[PyLibby](https://github.com/lullius/pylibby)

It's a CLI for Libby written in python. It can download audiobooks from Libby without the odm the same way as their online app does.

I mainly enjoy the part of programming that involves figuring out how stuff works, not so much the maintenance part, so please feel free to fork.

**Comment by chbrown** [comment]
Very cool :) will check it out when I can no longer use the `.odm` workflow.

FWIW, using a BSD / MIT / Apache 2 license is more amenable to forking, IMHO. If you have strong opinions about GPLv3, no problem — it's better than not releasing your code at all — but if your sentiment is something like "I made this cool thing that works for me and if other people want to take it and run with it, awesome" then I'd suggest relicensing 🤷‍♂️
