### ISSUE TITLE
Audiobook 'Borrow' button modal omits Download option

### ISSUE THREAD

**Issue by cerinawithasea** [chbrown/overdrive#64]
I think they just pulled the odms
everything was fine and all the sudden it only says listen now in browser. I have tried everything to get a download option on several diff laptops (win mac even an mi chip) no luck
Is it just me? (please let it just be me)

**Comment by crakerjac** [comment]
Well crap.... I'm seeing the same thing. I guess it was only a matter of time.

**Comment by TRezendes** [comment]
I came here to see if anyone else was seeing this. I am dismayed to find that others are.

**Comment by chbrown** [comment]
About a week ago they removed the download button from the direct book -> Borrow -> select # days -> Success! flow, but **you just need to bounce over to your Loans**, refresh if needed, and the "Have OverDrive for Mac/Windows?" > "Download MP3 audiobook" button still shows up there, same as before.

Or that's my experience at least... other libraries might be different?

**Comment by bedge** [comment]
Try using firefox. 
May just be your browser user-agent has been added to the list.
I'm still able to download the odm and pull mp3s

**Comment by windsifter** [comment]
Changing your user agent to mobile has always worked for me.

**Comment by grr** [comment]
this bookmarklet solution works fine: https://gist.github.com/ping/b58ae66359691db1d08f929a9e57a03d

**Comment by crakerjac** [comment]
> Well crap.... I'm seeing the same thing. I guess it was only a matter of time.

Refreshed the page this morning and it's back!

**Comment by cerinawithasea** [comment]
Scared me enough that i did nothing but download all weekend

**Comment by brianpipa** [comment]
Another easy solution I use... copy the Listen in Browser link, change
audiobook-overdrive to audiobook-mp3 in the URL
and that will download the ODM. The download script still works with this ODM.

**Comment by MidwestAhma** [comment]
> Another easy solution I use... copy the Listen in Browser link, change audiobook-overdrive to audiobook-mp3 in the URL and that will download the ODM. The download script still works with this ODM.

I just tried this (12/8/24) and it seems to work for the download, but when I try to open the file in Overdrive app, it crashes the app and says "error in the script": URL: https://www.googleoptimize.com/optimize.js?id=OPT-NQB32WG

Any ideas how to get around this?  Thanks in advance for any assistance.

**Comment by chbrown** [comment]
i'm not gonna click on your random shady-looking link

did you read https://github.com/chbrown/overdrive?tab=readme-ov-file#debugging ?

**Comment by MidwestAhma** [comment]
> i'm not gonna click on your random shady-looking link
> 
> did you read https://github.com/chbrown/overdrive?tab=readme-ov-file#debugging ?

Sorry -- I didn't intend that to be a link.  Just meant to list the error I got so that somebody WAY smarter than me could advise about a solution.

I followed your link but that's all way over my head.  I'm obviously a newbie and definitely not a coder.  Thanks for your response.

**Comment by MidwestAhma** [comment]
> Lasty, I will just say that this repo is very well documented, so there isn't much else to be said on how to use it. Get something that resembles a Unix shell, install the proper packages necessary through trial and error, and use this script until it stops working (likely in the near future).

Thank you for this additional information.  I would be willing to dig a little deeper into how to set up my system to run this script, but if, as you say, it will likely discontinue working in the near future, I don't really see the point.

If anyone gets crafty and figures out (or builds an "app") to download the .odm file into an MP3 format, I would be willing to donate to continue to have that capability.  I take care of many elderly people who enjoy their audiobooks borrowed from the library, but they only have old ipods or MP3 players on which to do so.  I have been loading those onto their old devices so that they can have that small pleasure in life.  They do not have smart phones or computers and wouldn't know what to do with them if they could even afford one. 

Thanks again for your help.

**Comment by chbrown** [comment]
> it will likely discontinue working in the near future, I don't really see the point

these days every time i trigger the request to download an odm file i cross my fingers and hold my breath thinking their latest update has more than likely put the final nail in the coffin

they haven't totally killed the functionality yet and imo shell scripting isn't a bad thing to learn in general, but based on what you're saying, yeah, this repo isn't for you, sorry

**Comment by bedge** [comment]
> Another easy solution I use... copy the Listen in Browser link, change audiobook-overdrive to audiobook-mp3 in the URL and that will download the ODM. The download script still works with this ODM.

@brianpipa This is fantastic bit of info. I'm at a loss as to why this post didn't pick up more responses. This is key to the solution that everyone's looking for.
A more automated solution would be to extract the session token from an `https://XXX.overdrive.com/account/loans`  login, scrape the "listen in browser" URL, and perform the substitution you mentioned, then you're done. Then you have the `.odm` amd the [overdrive.sh](https://github.com/chbrown/overdrive/blob/master/overdrive.sh) script still works.

thank you!!

**Comment by oranges13** [comment]
Here in February 2025 and appears that the url modification strategy above no longer works.

**Comment by brianpipa** [comment]
@oranges13 yep. I need it on my project too https://github.com/brianpipa/OverdriveMP3Downloader

**Comment by cerinawithasea** [comment]
I am now using https://github.com/HeronErin/LibbyRip with a converter that i wrote https://github.com/cerinawithasea/libregrab-m4b-creator
