### ISSUE TITLE
uuid replaced by uuidgen in mac OS 10.14

### ISSUE THREAD

**Issue by Diegus83** [chbrown/overdrive#7]
The script returns a License error since the command _uuid_ is not available in mac OS Mojave (10.14) and can't be easily installed via brew.
There is a similar command available _uuidgen_ that provides the same functionality (generating a random UUID).
A simple solution is to create an alias in bash _uudi -> uuidgen_ or replace the single use of _uuid_ in the script by _uuidgen_

**Comment by chbrown** [comment]
Good call. `uuidgen` seems pretty standard (i.e., widely available), so I don't know why I went with `uuid` originally. Fixed. Thanks :)
